metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of Windows Timeline (ActivitiesCache.db) artifact. Tool from Nihith (https://github.com/bolisettynihith/ActivitiesCacheParser)
  os: windows

configuration:
  module: win_timeline
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: unix

tool: 
  path: python
  cmd: /OSIR/OSIR/bin/ActivitiesCacheParser/ActivitiesCacheParser.py -f "{input_file}" --o "{output_dir}"
  source: https://github.com/maxspl/ActivitiesCacheParser
  version: 2025.09.30

input:
  type: file
  name: ActivitiesCache\.db$

output:
  type: multiple_files
  format: csv
  output_prefix: "{endpoint_name}--{module}-"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
  default: "UNKNOWN"