metadata:
  version: "1.0"
  author: maxspl
  description: Parsing of reg_keys - using ANSSI DFIR OGRE
  os: windows

configuration:
  module: ogre-hive-usrclass-dat
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
    - external
  processor_os: unix

tool: 
  path: /app/ogre-venv/bin/dfir-ogre
  cmd: >-
    plugin
    --filename "{input_file}"
    --computer_name "{endpoint_name}"
    --output_folder "{output_dir}"
    --plugin_config "/ogre/dfir-ogre-plugin-windows/configuration/hive.xml"
    --output_format jsonl
    --output_date_format iso_utc
    --params '{"root_name": "\\\\HKCR"}'
  source: https://github.com/ANSSI-FR/dfir-ogre
  version: 2.0.0-beta1

input:
  type: file
  paths:
    - r".*/UsrClass\.dat$"

output:
  type: multiple_files
  format: jsonl
  output_prefix: "{endpoint_name}-{user_name}--{module}-"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
    - r"\/Endpoint_(.*?)\/"
  default: "UNKNOWN"

user: 
  patterns:
    - r"Users\/([^\/]+)"
  default: "UNKNOWN"

splunk:
  'windows:ogre:hive_usrclass_dat':
    name_rex: '\.jsonl$'
    path_suffix: 'ogre-hive-usrclass-dat'
    sourcetype: 'windows:ogre:hive_usrclass_dat'
    host_rex: ([\w\.-]+)--
    artifact: "Hive Usrclass Dat"
    timestamp_path:
      - "mtime" 
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f%z"
