version: 1.0
author: 
module: arp
description: Kelly Brazil - JsonConverter - Parsing the output of the command arp or arp -a
os: unix
type: process
requirements:
disk_only: false
no_multithread: false
processor_type: 
  - external
processor_os: unix
tool: 
  path: cat
  cmd: "{input_file} | jc --arp | jq -c '.[]' > {output_file}"
input:
  type: file
  name: (?:arp)
  path: live_response/*
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:live_response:arp':
    name_rex: \.jsonl$
    path_suffix: arp
    sourcetype: 'linux:live_response:arp'
    host_rex: _([\w\.-]+)--
    artifact: "arp"