version: 1.0
author: 
module: ip_route
description: Kelly Brazil - JsonConverter - Parsing the output of the command ip route
os: unix
type: process
requirements:
disk_only: false
no_multithread: false
processor_type: 
  - external
processor_os: unix
tool: 
  path: cat
  cmd: "{input_file} | jc --ip-route | jq -c '.[]' > {output_file}"
input:
  type: file
  name: ip_route.txt$
  path: live_response/*
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:live_response:ip_route':
    name_rex: \.csv$
    path_suffix: 'amcache'
    sourcetype: 'windows:files:amcache'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "KeyLastWriteTimestamp"
        - "FileKeyLastWriteTimestamp"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "AmCache"