version: 1.0
author: 
module: lsmod
description: Kelly Brazil - JsonConverter - Parsing the output of the command lsmod
os: unix
type: process
requirements:
disk_only: false
no_multithread: false
processor_type: 
  - external
processor_os: unix
tool: 
  path: cat
  cmd: "{input_file} | jc --lsmod | jq -c '.[]' > {output_file}"
input:
  type: file
  name: (?:lsmod)\.txt$
  path: live_response/*
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:live_response:lsblk':
    name_rex: \.jsonl$
    path_suffix: lsmod
    sourcetype: 'linux:live_response:lsblk'
    host_rex: _([\w\.-]+)--
    artifact: lsblk