metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of recycle bin artifact.
  os: windows

configuration:
  module: recycle_bin
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: windows

tool: 
  path: net9/RBCmd.exe
  cmd: -d '{input_dir}' --csv "{output_dir}" --csvf "{output_file}" -q 
  source: https://github.com/EricZimmerman/RBCmd
  version: 1.6.0

input:
  type: dir
  path: $Recycle.Bin

output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'windows:recyclebin':
    name_rex: \.csv$
    path_suffix: 'recycle_bin'
    sourcetype: 'windows:files:recyclebin'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "DeletedOn"
    timestamp_format: "%Y-%m-%d %H:%M:%S"