# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-01-15T15:57:51+00:00

# TODO: Refactor API to group the class between client / API

from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class CaseCreateRequest(BaseModel):
    case_name: str = Field(..., title='Case Name')


class CreateCaseResponseCore(BaseModel):
    case_name: str = Field(..., title='Case Name')
    case_uuid: UUID = Field(..., title='Case Uuid')
    case_path: str = Field(..., title='Case Path')
    state: str = Field(..., title='State')


class GetCaseHandlerRequest(BaseModel):
    case_name: str = Field(..., title='Case Name')


class GetCaseResponseCore(BaseModel):
    cases: list[tuple[str, str]] = Field(..., title='Cases')


class GetHandlerStatusRequest(BaseModel):
    handler_id: UUID = Field(..., title='Handler Id')


class GetHandlerStatusResponseInfo(BaseModel):
    handler_id: UUID | None = Field(..., title='Handler Id')
    case_uuid: str | None = Field(..., title='Case Uuid')
    modules: list[str] | None = Field(..., title='Modules')
    task_ids: list[UUID] | None = Field(..., title='Task Ids')
    processing_status: str | None = Field(..., title='Processing Status')


class GetModuleResponseCore(BaseModel):
    modules: dict[str, Any] = Field(..., title='Modules')


class GetProfileResponseCore(BaseModel):
    profiles: list[str] = Field(..., title='Profiles')


class Json2ElasticModel(BaseModel):
    pass


class Json2SplunkConfigModel(BaseModel):
    source: str = Field(..., title='Source')
    sourcetype: str = Field(..., title='Sourcetype')
    name_rex: str = Field(..., title='Name Rex')
    path_suffix: str = Field(..., title='Path Suffix')
    host_rex: str = Field(..., title='Host Rex')
    timestamp_path: list[str] | None = Field(..., title='Timestamp Path')
    timestamp_format: str = Field(..., title='Timestamp Format')
    artifact: str = Field(..., title='Artifact')


class OsirConnectorModel(BaseModel):
    splunk: list[Json2SplunkConfigModel] | None = Field(..., title='Splunk')
    elastic: list[Json2ElasticModel] | None = Field(..., title='Elastic')


class Type(Enum):
    file = 'file'
    dir = 'dir'


class OsirInputModel(BaseModel):
    type: Type = Field(..., title='Type')
    path: str | None = Field(None, title='Path')
    name: str | None = Field(None, title='Name')
    file: str | None = Field(None, title='File')
    dir: str | None = Field(None, title='Dir')
    paths: list[str] | None = Field(None, title='Paths')
    match: Path | None = Field(None, title='Match')


class OsirIpcResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: dict[str, Any] | None = Field({}, title='Response')


class Os(Enum):
    windows = 'windows'
    unix = 'unix'
    ios = 'ios'
    macos = 'macos'
    network = 'network'
    android = 'android'
    generic = 'generic'


class Type1(Enum):
    pre_process = 'pre-process'
    process = 'process'
    post_process = 'post-process'
    post_parsing = 'post_parsing'


class ProcessorTypeEnum(Enum):
    internal = 'internal'
    external = 'external'


class ProcessorOs(Enum):
    windows = 'windows'
    unix = 'unix'


class OsirOutputModel(BaseModel):
    type: str | None = Field(None, title='Type')
    format: str | None = Field(None, title='Format')
    output_dir: str | None = Field(None, title='Output Dir')
    output_file: str | None = Field(None, title='Output File')
    output_prefix: str | None = Field(None, title='Output Prefix')


class OsirProfileModel(BaseModel):
    version: float | None = Field(None, title='Version')
    author: str | None = Field(None, title='Author')
    description: str | None = Field(None, title='Description')
    os: str | None = Field(None, title='Os')
    modules: list[str] = Field(..., title='Modules')


class OsirToolModel(BaseModel):
    path: str = Field(..., title='Path')
    cmd: str = Field(..., title='Cmd')
    source: str | None = Field(None, title='Source')
    version: str | float | None = Field(None, title='Version')
    license: str | None = Field(None, title='License')
    env: list[str] | None = Field(None, title='Env')


class RunModuleRequest(BaseModel):
    module_name: str = Field(..., title='Module Name')
    case_name: str = Field(..., title='Case Name')


class RunModuleResponseCore(BaseModel):
    handler_id: UUID = Field(..., title='Handler Id')


class RunProfileRequest(BaseModel):
    profile_name: str = Field(..., title='Profile Name')
    case_name: str = Field(..., title='Case Name')


class UnexpectedExceptionResponseCore(BaseModel):
    error: str = Field(..., title='Error')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class ApiHandlerGetHandlerStatusResponseCore(BaseModel):
    handler_id: UUID = Field(..., title='Handler Id')
    case_uuid: str = Field(..., title='Case Uuid')
    modules: list[str] = Field(..., title='Modules')
    task_ids: list[UUID] = Field(..., title='Task Ids')
    processing_status: str = Field(..., title='Processing Status')


class ApiHandlerGetHandlerStatusResponseCore2(BaseModel):
    handlers: list[GetHandlerStatusResponseInfo] = Field(..., title='Handlers')


class ApiHandlerGetHandlerStatusResponse2(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: ApiHandlerGetHandlerStatusResponseCore2


class CreateCaseResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: CreateCaseResponseCore


class GetCaseResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: GetCaseResponseCore


class GetModuleResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: GetModuleResponseCore


class GetProfileExistsResponseCore(BaseModel):
    exists: bool = Field(..., title='Exists')
    profile: OsirProfileModel


class GetProfileResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: GetProfileResponseCore


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class OsirModuleModel(BaseModel):
    version: float | str = Field(..., title='Version')
    author: str = Field(..., title='Author')
    module: str = Field(..., title='Module')
    description: str = Field(..., title='Description')
    os: Os = Field(..., title='Os')
    type: Type1 = Field(..., title='Type')
    disk_only: bool = Field(..., title='Disk Only')
    no_multithread: bool = Field(..., title='No Multithread')
    processor_type: list[ProcessorTypeEnum] = Field(..., title='Processor Type')
    processor_os: ProcessorOs = Field(..., title='Processor Os')
    optional: dict[str, Any] | None = Field(None, title='Optional')
    alt_module: str | None = Field(None, title='Alt Module')
    env: list[str] | None = Field(None, title='Env')
    tool: OsirToolModel | None = None
    input: OsirInputModel
    output: OsirOutputModel
    endpoint: str | None = Field(None, title='Endpoint')
    connector: OsirConnectorModel | None = None
    splunk: dict[str, Any] | None = Field(None, title='Splunk')


class RunModuleResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: RunModuleResponseCore


class UnexpectedExceptionResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: UnexpectedExceptionResponseCore


class ApiHandlerGetHandlerStatusResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: ApiHandlerGetHandlerStatusResponseCore


class GetModuleExistsResponseCore(BaseModel):
    exists: bool = Field(..., title='Exists')
    profile: OsirModuleModel


class GetProfileExistsResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: GetProfileExistsResponseCore


class GetModuleExistsResponse(BaseModel):
    version: float = Field(..., title='Version')
    status: int | None = Field(200, title='Status')
    message: str | None = Field(None, title='Message')
    response: GetModuleExistsResponseCore


class GetHandlerStatusResponseInfo(BaseModel):
    handler_id: Optional[UUID]
    # TODO: Replace with UUID after rework
    case_uuid: Optional[str]
    modules: Optional[list[str]]
    task_ids: Optional[list[UUID]]
    processing_status: Optional[str]


class GetHandlerListResponseCore(BaseModel):
    handlers: list[GetHandlerStatusResponseInfo]


class GetHandlerListResponse(OsirIpcResponse):
    response: GetHandlerListResponseCore


class GetHandlerStatusResponseCore(BaseModel):
    handler_id: UUID
    # TODO: Replace with UUID after rework
    case_uuid: str
    modules: list[str]
    task_ids: list[UUID]
    processing_status: str


class GetHandlerStatusResponse(OsirIpcResponse):
    response: GetHandlerStatusResponseCore
