metadata:
  version: "2.0"
  author: Typ
  description: Parse bash history from UAC [root] using Dissect plugin
  os: windows

configuration:
  module: bash_history
  alt_module: dissect_dispatcher
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: dir
  paths:
    - r"extract_uac.*\/\[root\]$"

output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/Endpoint_(.*?)\/"
  default: "UNKNOWN"

optional:
  plugin: bashhistory