version: 1.0
author: maxspl
module: age_decrypt
description: Used to decrypt age files. Don't forget to put the key in /OSIR/OSIR/configs/dependencies/encryption/key.age.
os: generic
type: pre-process
disk_only: True
no_multithread: True
processor_type: 
  - external
processor_os: unix
tool: 
  path: age
  source: 
  version: 
  cmd: >-
    --decrypt -i /OSIR/OSIR/configs/dependencies/encryption/key.age -o {output_dir}/{endpoint_name} {input_file} &&
    outdir="{output_dir}/$(printf '%s' "{endpoint_name}" | sed 's/\.tar\.gz$//')" &&
    mkdir -p "$outdir" &&
    tar -zxvf "{output_dir}/{endpoint_name}" -C "$outdir" &&
    mv "{input_file}" "{output_dir}/"
input:
  type: file
  paths: 
    - r"\.age$"
output:
  type: multiple_files
  format: raw
endpoint: \/([^\/]+)\.age