metadata:
  version: "2.0"
  author: maxspl
  description: Used to decrypt age files. Don't forget to put the key in /OSIR/OSIR/configs/dependencies/encryption/key.age.
  os: generic

configuration:
  module: age_decrypt
  type: pre-process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: age
  source: 
  version: 
  cmd: >-
    --decrypt -i /OSIR/OSIR/configs/dependencies/encryption/key.age -o {output_dir}/{endpoint_name} {input_file} &&
    outdir="{output_dir}/$(printf '%s' "{endpoint_name}" | sed 's/\.tar\.gz$//')" &&
    mkdir -p "$outdir" &&
    tar -zxvf "{output_dir}/{endpoint_name}" -C "$outdir" &&
    mv "{input_file}" "{output_dir}/"

input:
  type: file
  paths: 
    - r"\.age$"

output:
  type: multiple_files
  format: raw

endpoint: 
  patterns:
    - r"\/([^\/]+)\.age"
  default: "NOT_FOUND"