version: 1.0
author: maxspl
module: dfir_orc_decrypt
description: Used to decrypt age files. Don't forget to put the key in /OSIR/OSIR/configs/dependencies/encryption/DFIRORC_key.pem.
os: windows
type: pre-process
disk_only: True
no_multithread: True
processor_type: 
  - external
processor_os: unix
tool: 
  path: orc-decrypt-rs
  source: 
  version: 
  cmd: -k /OSIR/OSIR/configs/dependencies/encryption/DFIRORC_key.pem --output-dir {output_dir}/{endpoint_name} {input_file}
input:
  type: file
  paths: 
    - r"\.7z\.p7b$"
output:
  type: multiple_files
  format: raw
endpoint: DFIR-ORC_(?:Server|WorkStation|DomainController)_((?:\w|-|\.)+)_(\w+)\.7z\.p7b$