metadata:
  version: "2.0"
  author: maxspl
  description: Used to decrypt age files. Don't forget to put the key in /OSIR/OSIR/configs/dependencies/encryption/DFIRORC_key.pem.
  os: windows

configuration:
  module: dfir_orc_decrypt
  type: pre-process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: orc-decrypt-rs
  source: 
  version: 
  cmd: -k /OSIR/OSIR/configs/dependencies/encryption/DFIRORC_key.pem --output-dir {output_dir}/{endpoint_name} {input_file}

input:
  type: file
  paths: 
    - r"\.7z\.p7b$"

output:
  type: multiple_files
  format: raw

endpoint: 
  patterns:
    - r"DFIR-ORC_(?:Server|WorkStation|DomainController)_((?:\w|-|\.)+)_(\w+)\.7z\.p7b$"
  default: "NOT_FOUND"