metadata:
  version: "2.0"
  author: Typ
  description: Used to execute internal pre-processing for Unix Artefact Collector
    Capture
  os: unix

configuration:
  module: extract_uac
  type: pre-process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  processor_os: unix

tool: 
  path: tar
  version: 22.01
  cmd: -xvf {input_file} -C {output_dir}

input:
  type: file
  paths:
    - uac-*.tar.gz

output:
  type: multiple_files
  format: raw
  output_dir: Endpoint_{endpoint_name}/extracted_files

endpoint: 
  patterns:
    - r"(?:.*[\\/])?[^-]+-(.*)-[^-]+-[^-]+$"
  default: "UNKNOWN"
