metadata:
  version: "2.0"
  author: maxspl
  description: Used to execute internal pre-processing for DFIR-ORC capture
  os: windows

configuration:
  module: extract_orc
  type: pre-process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  - external
  processor_os: unix

tool: 
  path: 7zz
  source: 
  version: 24.07
  cmd: x -o{m_output_dir} -y {m_input_file} -p"{optional_password}"
input:
  type: file
  paths:
    - r"DFIR-ORC(?:-\w+)?_(?:Server|WorkStation|DomainController)_([\w.\-]+?)(?:_\w+)*\.(?:7z|json|log)$"
output:
  type: multiple_files
  format: raw
optional:
  password: avproof
splunk:
  'windows:live_response:systeminfo':
      name_rex: (?i)^systeminfo(?:_.+)?\.csv$
      path_rex: '.*\/extract_orc.*'
      host_rex: "\/Endpoint_(.*?)\/"
      sourcetype: _json               
      timestamp_path:
        - "timestamp" 
      timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
      normalize:
        - ecs_normalize/windows/live_response/systeminfo.vrl    
  'windows:live_response:processes':
      name_rex: (?i)(?:^|/)processes(?:\d+|_[^/]+)?\.csv$
      path_rex: '.*\/extract_orc.*'
      host_rex: "\/Endpoint_(.*?)\/"
      sourcetype: _json          
      timestamp_path:
        - "timestamp" 
      timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
      normalize:
        - ecs_normalize/windows/live_response/ps1_processes.vrl         
  'filesystem:ntfs:info':
    name_rex: NTFSInfo.*.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'filesystem:ntfs:info'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    encoding: utf-8
    normalize:
      - ecs_normalize/windows/NTFSInfo.vrl        
  'filesystem:ntfs:usn':
    name_rex: USNInfo.*.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'filesystem:ntfs:usn'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "TimeStamp"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'filesystem:ntfs:i30':
    name_rex: I30Info.*.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'filesystem:ntfs:i30'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    encoding: utf-8
    normalize:
      - ecs_normalize/windows/NTFSInfo_i30.vrl
  'windows:live_response:autoruns':
    name_rex: autoruns.*csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'windows:autoruns'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/live_response/autoruns.vrl                   
  'orc:collected_files':
    name_rex: GetThis.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'orc:collected_files'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "CreationDate"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'orc:csv':
    name_rex: \.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'orc:files'
    host_rex: "\/Endpoint_(.*?)\/"
    artifact: "Orc"