metadata:
  version: "2.0"
  author: maxspl
  description: Used to execute DFIR ORC on dd capture
  os: windows

configuration:
  module: orc_offline
  type: pre-process
  disk_only: false
  no_multithread: true
  processor_type:
  - external
  processor_os: windows

tool: 
  path: python.exe
  cmd: >-
    {drive}\OSIR\bin\dfir_orc_offline\DFIR_ORC_wrapper.py
    -i "{input_file}" -o "{output_dir}" -e "{endpoint_name}"
  source: https://github.com/dfir-orc
  version: latest

input:
  type: file
  name: \.dd$
  path: r"\/[^\/]+--"

output:
  type: multiple_files
  format: raw

endpoint: 
  patterns:
    - r"\/([^\/]+)--"
  default: "UNKNOWN"