metadata:
  version: "2.0"
  author: Typ
  description: Used to mount vhdx file system.
  os: unix

configuration:
  module: vhdx
  type: pre-process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: target-mount
  cmd: "{input_file} {output_dir}"
  source: https://github.com/fox-it/dissect
  version: 3.2.1

input:
  type: file
  paths: 
    - r"\.vhdx$"

output:
  type: None
  output_dir: "{case_path}/virtual/Endpoint_{endpoint_name}"

endpoint: 
  patterns:
    - r"([^\/]+).vhdx"
  default: "UNKNOWN"