version: 1.0
author: maxspl
module: activities_cache
alt_module: dissect_dispatcher
description: Parse ActivitiesCache.db from DFIR ORC restore_fs using Dissect plugin
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - internal
processor_os: unix
input:
  type: dir
  path: r"restore_fs\/[^\/]*$"
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "restore_fs\/(.*?)$"
optional:
  plugin: activitiescache
splunk:
  'windows:activitiescache':
    name_rex: --activities_cache\.jsonl$
    host_rex: ([\w\.-]+)--
    path_suffix: activities_cache
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "ActivitiesCache"
    normalize:
      - ecs_normalize/windows/activities_cache.vrl    
      