metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of browsers artifact.
  os: windows

configuration:
  module: browsers
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: unix

tool: 
  path: python
  cmd: /OSIR/OSIR/bin/BrowserParser/main.py {input_dir} {output_dir} --json
  source: https://github.com/seba7236/BrowserParser
  version: 1.0.1

input:
  type: dir
  path: r"restore_fs\/[^\/]+\/C$"

output:
  type: multiple_files
  format: jsonl
  output_prefix: "{endpoint_name}--{module}-"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'application:firefox':
    name_rex: .*firefox.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:firefox'
    host_rex: ([\w\.-]+)--
  'application:chrome':
    name_rex: .*chrome.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:chrome'
    host_rex: ([\w\.-]+)--
  'application:edge':
    name_rex: .*edge.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:edge'
    host_rex: ([\w\.-]+)--