metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of browsers artifact.
  os: windows

configuration:
  module: browsers
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: unix

tool: 
  path: python
  cmd: /OSIR/OSIR/bin/BrowserParser/main.py "{input_dir}" "{output_dir}" --csv
  source: https://github.com/maxspl/BrowserParser
  version: 1.1.0

input:
  type: dir
  path: r"restore_fs\/[^\/]+\/C$"

output:
  type: multiple_files
  format: jsonl
  output_prefix: "{extracted_endpoint}--{module}-"

extracted:
  - endpoint:
      patterns:
        - r"restore_fs\/(.*?)\/"
      default: "UNKNOWN"

splunk:
  'application:firefox':
    name_rex: r".*firefox.*\.csv$"
    path_suffix: 'browsers'
    sourcetype: 'application:browser:firefox'
    host_rex: r"([\w\.-]+)--"
    user_rex: r"browsers-([^-_]+)_"
    timestamp_path:
      - "timestamp"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/browsers.vrl
  'application:chrome':
    name_rex: r".*chrome.*\.csv$"
    path_suffix: 'browsers'
    sourcetype: 'application:browser:chrome'
    host_rex: r"([\w\.-]+)--"
    user_rex: r"browsers-([^-_]+)_"
    timestamp_path:
      - "timestamp"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/browsers.vrl
  'application:edge':
    name_rex: r".*edge.*\.csv$"
    path_suffix: 'browsers'
    sourcetype: 'application:browser:edge'
    host_rex: r"([\w\.-]+)--"
    user_rex: r"browsers-([^-_]+)_"
    timestamp_path:
      - "timestamp"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/browsers.vrl
