version: 1.0
author:
module: browsers
description: Parsing of browsers artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: unix
tool: 
  path: python
  cmd: /OSIR/OSIR/bin/BrowserParser/main.py {input_dir} {output_dir} --json
  source: https://github.com/seba7236/BrowserParser
  version: 1.0.1
input:
  type: dir
  path: r"restore_fs\/[^\/]+\/C$"
output:
  type: multiple_files
  format: jsonl
  output_prefix: "{endpoint_name}--{module}-"
endpoint: "restore_fs\/(.*?)\/"
splunk:
  'application:firefox':
    name_rex: .*firefox.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:firefox'
    host_rex: ([\w\.-]+)--
  'application:chrome':
    name_rex: .*chrome.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:chrome'
    host_rex: ([\w\.-]+)--
  'application:edge':
    name_rex: .*edge.*\.json$
    path_suffix: 'browsers'
    sourcetype: 'application:browser:edge'
    host_rex: ([\w\.-]+)--