version: 1.0
author:
module: collect_info_orc
description: Hash of DFIR ORC collected file
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: unix
tool: 
  path: /usr/bin/find
  cmd:  -P {input_dir} -name "DFIR-ORC_*.7z" -exec sh -c
    'sha1=$(sha1sum "$1" | awk "{print \$1}");
    birth=$(stat -c %W "$1");
    [ "$birth" = "-1" ] && birth=$(stat -c %Y "$1");
    jq -n -c --arg sha1 "$sha1" --arg date "$birth" --arg name "$(basename "$1")" "{sha1:\$sha1,date:\$date,name:\$name}"' sh {} \;
    > {output_file}
input:
  type: dir
  path: extract_orc/*
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "Endpoint_(.*?)$"
splunk:
  'collect:info':
    name_rex: \.jsonl$
    path_suffix: collect_info_orc
    sourcetype: 'collect:info'
    host_rex: ([\w\.-]+)--
    timestamp_path:
        - "date"
    timestamp_format: "%s"
    artifact: info