version: 1.0
author:
module: hives_hklm
description: Parsing of registry hives artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: windows
tool: 
  path: net9/RECmd/RECmd.exe
  cmd: -d "{input_dir}" --csv "{output_dir}" --csvf "{output_file}" --bn "{drive}\OSIR\bin\net9\RECmd\BatchExamples\DFIRBatch.reb" --recover
  source:
  version: 
input:
  type: dir
  path: Windows/System32/config
output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"
endpoint: "restore_fs\/(.*?)\/"
splunk:
  'windows:hklm':
    name_rex: --hives_*\w*\.csv
    path_rex: '.*\/hives_hklm.*'
    sourcetype: 'windows:registry:hklm'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "LastWriteTimestamp"
        - "Timestamp"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
    artifact: "Hives"