version: 1.0
author: maxspl
module: jump_list
description: Parsing of jump list artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: windows
tool: 
  path: net9/JLECmd.exe
  cmd: -d "{input_dir}" --csv "{output_dir}" --csvf "{output_file}" -q --all --fd
  source: https://ericzimmerman.github.io/
  version: 1.5
input:
  type: dir
  path: Artefacts/recentFile
output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"
endpoint: "/Endpoint_(.*?)/"
splunk:
  'windows:jumplist':
    name_rex: \.csv$
    path_suffix: 'jump_list'
    sourcetype: 'windows:files:jumplist'
    host_rex: ([\w\.-]+)--
    artifact: "JumpList"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/jump_list.vrl