version: 1.0
author:
module: lnk
description: Parsing of lnk artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: windows
tool: 
  path: net9/LECmd.exe
  cmd: -d "{input_dir}" --csv "{output_dir}" --csvf "{output_file}" -q --all
  source:
  version: 
input:
  type: dir
  path: Artefacts/lnk
output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"
endpoint: "/Endpoint_(.*?)/"
splunk:
  'windows:lnk':
    name_rex: \.csv$
    path_suffix: 'lnk'
    sourcetype: 'windows:files:lnk'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "SourceModified"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
    artifact: "Lnk"
