metadata:
  version: "2.0"
  author: maxspl
  description: Parse processes1.csv to produce pstree
  os: windows

configuration:
  module: pstree_live_response
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: unix

tool: 
  path: python
  cmd: OSIR/OSIR/bin/log2pstree/log2pstree.py --input {input_file} --pid-path "ProcessId" --ppid-path "ParentProcessId" --exe-path "ProcessName" --cmdline-path "CommandLine" --time-path "CreationDate" --output-dir {output_dir}
  source: https://github.com/maxspl/log2pstree
  version: 2025.08.07

input:
  type: file
  paths: 
    - "**/extracted_files/Powershell/processes1.csv"
    - "**/extracted_files/powershell/processeswmi*.csv"

output:
  type: multiple_files
  format: jsonl
  output_prefix: "{endpoint_name}--{module}-"

endpoint: 
  patterns:
    - r"/Endpoint_(.*?)/"
  default: "UNKNOWN"

splunk:
  'windows:live_response:pstree':
    name_rex: nodes\.jsonl$
    path_suffix: 'pstree_live_response'
    sourcetype: 'windows:live_response:pstree'
    host_rex: ([\w\.-]+)--
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "pstree_live_response"
    normalize:
      - ecs_normalize/windows/pstree_nodes.vrl    