version: 1.0
author:
module: recycle_bin
description: Parsing of recycle bin artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: windows
tool: 
  path: net6/RBCmd.exe
  cmd: -d "{input_dir}" --csv "{output_dir}" --csvf "{output_file}" -q 
  source:
  version: 
input:
  type: dir
  path: $Recycle.Bin
output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"
endpoint: "restore_fs\/(.*?)\/"
splunk:
  'windows:recyclebin':
    name_rex: \.csv$
    path_suffix: 'recycle_bin'
    sourcetype: 'windows:files:recyclebin'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "DeletedOn"
    timestamp_format: "%Y-%m-%d %H:%M:%S"