metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of shell bags artifact.
  os: windows

configuration:
  module: shell_bags
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: windows

tool: 
  path: net9/SBECmd.exe
  cmd: -d "{input_dir}" --csv "{output_dir}" --csvf "{output_file}"
  source: https://ericzimmerman.github.io/
  version: 2.1.0

input:
  type: dir
  path: Users/

output:
  type: single_file
  format: csv
  output_file: "{endpoint_name}--{module}.csv"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'windows:shellbags':
    name_rex: \.csv$
    path_suffix: 'shell_bags'
    sourcetype: 'windows:registry:hku:shellbags'
    host_rex: _UsrClass_(.*)--shell_bags.csv
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "ShellBags"
    normalize:
      - ecs_normalize/windows/shell_bags.vrl   