metadata:
  version: "2.0"
  author: maxspl
  description: Parse .wer files
  os: windows

configuration:
  module: wer
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: dir
  path: ProgramData/Microsoft/Windows/WER/

output:
  type: single_file
  format: jsonl
  filename: "{extracted_endpoint}--{module}.jsonl"

extracted:
  - endpoint:
      patterns:
        - r"restore_fs\/(.*?)\/"
      default: "UNKNOWN"

splunk:
  'windows:wer':
    name_rex: r"--wer\.jsonl$"
    path_suffix: 'wer'
    host_rex: r"([\w\.-]+)--"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "WER"
    normalize:
      - ecs_normalize/windows/wer.vrl
