metadata:
  version: "2.0"
  author: maxspl
  description: Parsing of Windows memory dump.
  os: windows

configuration:
  module: win_memory
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  - external
  processor_os: unix

tool: 
  path: memprocfs/memprocfs
  source: https://github.com/ufrisk/MemProcFS
  version: v5.17.4
  cmd: -device {input_file} -pythonexec {pythonexec_path} -forensic 1

input:
  type: file
  path: Memory/
  name: \.ram$

output:
  type: multiple_files
  format: jsonl

endpoint: 
  patterns:
    - r"/Endpoint_(.*?)/"
  default: "UNKNOWN"

splunk:
  'windows:live_response:memory:devices':
    name_rex: devices
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:device'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:device"
  'windows:live_response:memory:drivers':
    name_rex: drivers
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:drivers'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:drivers"
  'windows:live_response:memory:files':
    name_rex: files
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:files'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:files"
  'windows:live_response:memory:findevil':
    name_rex: findevil
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:findevil'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:findevil"
  'windows:live_response:memory:general':
    name_rex: general
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:general'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:general"
  'windows:live_response:memory:handles':
    name_rex: handles
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:handles'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:handles"
  'windows:live_response:memory:modules':
    name_rex: modules
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:modules'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:modules"
  'windows:live_response:memory:net':
    name_rex: net
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:net'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S UTC"
    artifact: "Memprocfs:net"
  'windows:live_response:memory:prefetch':
    name_rex: prefetch
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:prefetch'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "RunTime1"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:prefetch"
  'windows:live_response:memory:process':
    name_rex: process
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:process'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "CreateTime"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:process"
  'windows:live_response:memory:registry':
    name_rex: registry
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:registry'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "lastwrite"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "Memprocfs:registry"
  'windows:live_response:memory:services':
    name_rex: services
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:services'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:services"
  'windows:live_response:memory:sysinfo':
    name_rex: sysinfo
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:sysinfo'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:sysinfo"
  'windows:live_response:memory:tasks':
    name_rex: tasks
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:tasks'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "TimeCreate"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:tasks"
  'windows:live_response:memory:threads':
    name_rex: threads
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:threads'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "CreateTime"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:threads"
  'windows:live_response:memory:timeline_all':
    name_rex: timeline_all
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_all'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_all"
  'windows:live_response:memory:timeline':
    name_rex: timeline.json
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "date"
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline"
  'windows:live_response:memory:timeline_kernelobject':
    name_rex: timeline_kernelobject
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_kernelobject'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_kernelobject"
  'windows:live_response:memory:timeline_net':
    name_rex: timeline_net
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_net'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_net"
  'windows:live_response:memory:timeline_ntfs':
    name_rex: timeline_ntfs
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_ntfs'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_ntfs"
  'windows:live_response:memory:timeline_prefetch':
    name_rex: timeline_prefetch
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_prefetch'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_prefetch"
  'windows:live_response:memory:timeline_process':
    name_rex: timeline_process
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_process'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_process"
  'windows:live_response:memory:timeline_registry':
    name_rex: timeline_registry
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_registry'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_registry"
  'windows:live_response:memory:timeline_task':
    name_rex: timeline_task
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_task'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_task"
  'windows:live_response:memory:timeline_thread':
    name_rex: timeline_thread
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_thread'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_thread"
  'windows:live_response:memory:timeline_web':
    name_rex: timeline_web
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:timeline_web'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:timeline_web"
  'windows:live_response:memory:unloaded_modules':
    name_rex: unloaded_modules
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:unloaded_modules'
    host_rex: win_memory\/(.*?)\/
    timestamp_path: 
        - "UnloadTime"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "Memprocfs:unloaded_modules"
  'windows:live_response:memory:virtualmachines':
    name_rex: virtualmachines
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:virtualmachines'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:virtualmachines"
  'windows:live_response:memory:yara':
    name_rex: yara
    path_rex: "win_memory\/[^\/]+$"
    sourcetype: 'windows:live_response:memory:ram:yara'
    host_rex: win_memory\/(.*?)\/
    artifact: "Memprocfs:yara"