metadata:
  version: "2.0"
  author: Kelly Brazil
  description: Kelly Brazil - JsonConverter - Parsing the output of the command free
  os: unix

configuration:
  module: free
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - external
  processor_os: unix

tool: 
  path: cat
  cmd: "{input_file} | jc --free | jq -c '.[]' > {output_file}"

input:
  type: file
  paths:
    - r"free\.txt$"

output:
  type: single_file
  format: jsonl
  output_dir: "{case_path}/live_response/system" 
  output_file: "{endpoint_name}--{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:live_response:system:free':
    name_rex: \.jsonl$
    path_suffix: free
    sourcetype: 'linux:live_response:system:free'
    host_rex: _([\w\.-]+)--
    artifact: free