metadata:
  version: "2.0"
  author: maxspl
  description: Splunk logs ingestion (ORC) using json2splunk configuration from dependencies/orc_indexer_patterns.yml
  os: windows

configuration:
  module: orc_indexer
  type: post-process
  disk_only: false
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: python
  cmd: /OSIR/OSIR/bin/json2splunk/json2splunk.py --input {input_dir} --index {case_name} --config_spl /OSIR/setup/conf/agent.yml --indexer_patterns /OSIR/OSIR/configs/dependencies/orc_indexer_patterns.yml
  source: https://github.com/maxspl/json2splunk
  version: 1.25.06.2024

input:
  type: dir
  path: "{case_path}"

output:
  type: None

