version: 1.1
author:
module: extract_orc
description:
os: windows
type: pre-process
disk_only: True
no_multithread: True
processor_type: 
  - internal
  - external
processor_os: unix
tool: 
  path: 7zz
  source: 
  version: 24.07
  cmd: x -o{output_dir} -y {input_file} -p"{optional_password}"
input:
  type: file
  name: ^DFIR-ORC_(?:Server|WorkStation|DomainController)_((?:\w|-|\.)+)_(\w+)\.7z$
output:
  type: multiple_files
  format: raw
optional:
  password: avproof
splunk:
  'filesystem:ntfs:info':
    name_rex: NTFSInfo.*.csv$
    path_rex: '.*\/NTFSInfo.*'
    sourcetype: 'filesystem:ntfs:info'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "FileNameLastModificationDate"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'filesystem:ntfs:usn':
    name_rex: USNInfo.*.csv$
    path_rex: '.*\/USNInfo.*'
    sourcetype: 'filesystem:ntfs:usn'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "TimeStamp"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'filesystem:ntfs:i30':
    name_rex: I30Info.*.csv$
    path_rex: '.*\/NTFSInfo.*i30Info.*'
    sourcetype: 'filesystem:ntfs:i30'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "FileNameCreationDate"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'windows:autoruns':
    name_rex: autoruns.csv$
    path_suffix: 'General'
    sourcetype: 'windows:autoruns'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "Time"
    timestamp_format: "%Y%m%d-%H%M%S"
  'orc:collected_files':
    name_rex: GetThis.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'orc:collected_files'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "CreationDate"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
  'orc:csv':
    name_rex: \.csv$
    path_rex: '.*\/extract_orc.*'
    sourcetype: 'orc:files'
    host_rex: "\/Endpoint_(.*?)\/"
    artifact: "Orc"