version: 1.1
author: Typ
module: extract_uac
description: Used to execute internal pre-processing for Unix Artefact Collector Capture 
os: unix
type: pre-process
requirements:
disk_only: True
no_multithread: True
processor_type: 
  - internal
processor_os: unix
tool: 
  path: tar
  version: 22.01
  cmd: -xvf {input_file} -C {output_dir}
input:
  type: file
  paths:
    - uac-*.tar.gz
output:
  type: multiples_files
  format: raw
  output_dir: Endpoint_{endpoint_name}/extracted_files
endpoint: (?:.*[\\/])?[^-]+-(.*)-[^-]+-[^-]+$