metadata:
  version: "2.0"
  author: maxspl
  description: Parse arp_cache.txt from DFIR ORC (arp -a command)
  os: windows

configuration:
  module: win_arp_cache
  alt_module: live_response_dispatcher
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  paths:
    - "**/extracted_files/General/arp_cache.txt"
    - r"arpcache_.*\.txt$"

output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"

endpoint: 
  patterns:
    - r"/Endpoint_(.*?)/"
  default: "UNKNOWN"

optional:
  parser: arp_cache

splunk:
  'windows:live_response:arp_cache':
    name_rex: --win_arp_cache\.jsonl$
    path_suffix: 'win_arp_cache'
    host_rex: ([\w\.-]+)--
    artifact: "ARP"
    normalize:
      - ecs_normalize/windows/live_response/arp_cache.vrl