version: 1.0
author: maxspl
module: win_netstat
alt_module: live_response_dispatcher
description: Parse netstat.txt from DFIR ORC (netstat.exe -a -n -o command)
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: netstat.txt
  path: extracted_files/General/
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "/Endpoint_(.*?)/"
optional:
  parser: netstat
splunk:
  'windows:live_response:netstat':
    name_rex: --win_netstat\.jsonl$
    path_suffix: win_netstat 
    host_rex: ([\w\.-]+)--
    artifact: "NETSTAT"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - normalize/windows/live_response/netstat.vrl   