version: 1.0
author: maxspl
module: win_listdlls
alt_module: live_response_dispatcher
description: Parse Listdlls.txt from DFIR ORC (Listdlls.exe command)
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  paths: 
    - "**/extracted_files/General/Listdlls.txt"
    - r"listdlls_.*\.txt$" 
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "/Endpoint_(.*?)/"
optional:
  parser: listdlls
splunk:
  'windows:live_response:dll':
    name_rex: --win_listdlls\.jsonl$
    path_suffix: win_listdlls 
    host_rex: ([\w\.-]+)--
    artifact: "DLL"
    timestamp_path:
      - "timestamp" 
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    normalize:
      - ecs_normalize/windows/live_response/listdlls.vrl      