version: 1.0
author: maxspl
module: win_dns_records
alt_module: live_response_dispatcher
description: Parse DNS_records.txt from DFIR ORC (custom ps1 command)
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: DNS_records.txt
  path: extracted_files/Powershell/
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "/Endpoint_(.*?)/"
optional:
  parser: dns_records