version: 1.0
author: maxspl
module: win_handle
alt_module: live_response_dispatcher
description: Parse handle from DFIR ORC (handle.exe /a command)
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: handle.txt
  path: extracted_files/General/
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "/Endpoint_(.*?)/"
optional:
  parser: handle