version: 1.0
author:
module: thor_lite
description: Scan of collected file using Thor Lite.
os: all
type: process
disk_only: False
no_multithread: True
processor_type: 
  - external
processor_os: unix
tool: 
  path: thor-lite/thor-lite-linux-64
  cmd: -a Filescan --intense --norescontrol --cross-platform -p {input_dir} --nocsv --silent --nolog --jsonfile {output_file} 
  source: https://www.nextron-systems.com/thor-lite/
  version: 1.0
input:
  type: dir
  path: extracted_files
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}.jsonl"
endpoint: "/Endpoint_(.*?)/"
splunk:
  'thor:files':
    name_rex: \.jsonl$
    path_suffix: 'thor_lite'
    sourcetype: 'thor:files'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "time"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "Thor"