metadata:
  version: "2.0"
  author: maxspl
  description: Scan of RAM restored file system from MemProcFS using Thor (requires
    Forensic license).
  os: generic

configuration:
  module: thor_orc_ram
  type: process
  disk_only: false
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: thor/thor-linux-64
  cmd: --lab --nocsv --silent --nolog -p {input_dir} --jsonfile {output_file}
  source: https://www.nextron-systems.com/thor/
  version: 1.0

input:
  type: dir
  path: win_memory/*

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-ram.jsonl"

endpoint: 
  patterns:
    - r"win_memory\/(.*?)--win_memory-restore_fs-ram"
  default: "UNKNOWN"

splunk:
  'thor:memory':
    name_rex: \.jsonl$
    path_suffix: 'thor_orc_ram'
    sourcetype: 'thor:memory'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "time"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "Thor"
