version: 1.0
author: Kelly Brazil
module: snap
description: Kelly Brazil - JsonConverter - Parsing the output of the command snap
os: unix
type: process
requirements:
disk_only: false
no_multithread: false
processor_type: 
  - external
processor_os: unix
tool: 
  path: cat
  cmd: "{input_file} | jc --asciitable | jq -c '.[]' > {m_output_file}"
input:
  type: file
  paths: 
    - r"snap_list_--all\.txt$"
    - r"snap_list\.txt$"
output:
  type: single_file
  format: jsonl
  output_dir: "{case_path}/live_response/packages"
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:live_response:dpkg':
    name_rex: snap.*\.jsonl$
    sourcetype: 'linux:live_response:packages:snap'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "_time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: snap
    normalize:
      - ecs_normalize/linux/live_response/packages/snap.vrl