metadata:
  version: "1.0"
  author: Grand-Duc
  description: ElasticSearch ingestion (DFIR ORC and UAC) using the same module-specific
    datamodel and VRL normalization as the Splunk indexer.
  os: generic

configuration:
  module: indexer_elastic
  type: post_parsing
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

tool:
  path: json2elastic-rs
  cmd: >-
    --input {input_dir_replaced_by_internal_module}
    --index {case_name}
    --config /OSIR/setup/conf/agent.yml
    --indexer_patterns {indexer_path}
    --vrl_dir /OSIR/OSIR/configs/dependencies/
  source: https://github.com/Grand-Duc/json2elastic-rs/releases
  version: 1.0

input:
  type: dir
  path: "{case_path}"

output:
  type: single_file
  format: jsonl
