metadata:
  version: "1.0"
  author: typ
  description: Splunk logs ingestion (DFIR ORC and UAC) using module-specific json2splunk-rs
    configuration.
  os: generic

configuration:
  module: indexer_ng
  type: post_parsing
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

tool: 
  path: json2splunk-rs
  cmd: >-
    --input {input_dir_replaced_by_internal_module} --index {case_name} --config_spl /OSIR/setup/conf/agent.yml 
    --indexer_patterns {indexer_path} --vrl_dir /OSIR/OSIR/configs/dependencies/
  source: https://github.com/maxspl/json2splunk-rs/releases
  version: 1.4

input:
  type: file
  path: "{case_path}"

output:
  type: single_file
  format: jsonl
