version: 1.0
author: Typ
module: bodyfile
description: Parsing logs from '/bodyfile' in UAC collect
os: unix
type: process
requirements:
disk_only: True
no_multithread: True
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  paths: 
    - "bodyfile/*.txt"
    - "**/bodyfile/*.txt"
    - r"bodyfile.txt$"
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"
endpoint: "extract_uac\/Endpoint_(.*?)\/"
splunk:
  'linux:files:bodyfile':
    name_rex: bodyfile.*\.jsonl$
    sourcetype: 'linux:files:bodyfile'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "mtime"
    timestamp_format: "%s"
    artifact: "bodyfile"