version: 1.0
author:
module: cron
description: Parsing logs from '/var/log/cron'
os: unix
type: process
requirements:
disk_only: True
no_multithread: True
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: (?:cron)
  path: var/log
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:cron':
    name_rex: ^cron.*?\.jsonl$
    sourcetype: 'linux:cron'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "_time"
    timestamp_format: "%b %d %H:%M:%S"
    artifact: "cron"