metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/cron'
  os: unix

configuration:
  module: cron
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  name: (?:cron)
  path: var/log

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:cron':
    name_rex: ^cron.*?\.jsonl$
    sourcetype: 'linux:cron'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "_time"
    timestamp_format: "%b %d %H:%M:%S"
    artifact: "cron"