metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/debug'
  os: unix

configuration:
  module: debug
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  path: var/log
  name: (?:debug)

output:
  type: single_file
  format: json
  output_file: '{endpoint_name}--{module}-{input_file}.jsonl'

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

