version: 1.0
author:
module: dpkg
description: Parsing logs from '/var/log/dpkg'
os: unix
type: process
requirements:
disk_only: True
no_multithread: True
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: (?:dpkg)
  path: var/log
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:dpkg':
    name_rex: dpkg.*\.jsonl$
    sourcetype: 'linux:dpkg'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "_time"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    artifact: "dpkg"