metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/journal/'
  os: unix

configuration:
  module: journal
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: journalctl
  cmd: --file={input_file} --output=json > {output_file}

input:
  type: file
  name: (?:system|user)
  path: var/log/journal/*

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:journal':
    name_rex: \.jsonl$
    path_suffix: journal
    sourcetype: 'linux:journal'
    host_rex: _([\w\.-]+)--
    timestamp_path: 
        - "__REALTIME_TIMESTAMP"
    artifact: "journal"
