metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/lastlog'
  os: unix

configuration:
  module: lastlog
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  name: (?:lastlog)
  path: var/log/

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:lastlog':
    name_rex: lastlog.*\.jsonl$
    sourcetype: 'linux:lastlog'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
        - "_time"
    timestamp_format: "%Y/%m/%d %H:%M:%S"
    artifact: "lastlog"
