metadata:
  version: "3.0"
  author: Typ,maxspl
  description: Parsing logs from '/bodyfile' in UAC collect
  os: unix

configuration:
  module: mactime
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: TurboLP
  cmd: run --module mactime --input "{input_file}" --output {output_file}

input:
  type: file
  paths: 
    - "bodyfile/*.txt"
    - "**/bodyfile/*.txt"
    - r"\/bodyfile\.txt$"

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/Endpoint_(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:files:bodyfile':
    name_rex: bodyfile.*\.jsonl$
    sourcetype: 'linux:files:bodyfile'
    host_rex: ([\w\.-]+)--
    timestamp_path: 
        - "timestamp"
    timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
    artifact: "bodyfile"
    normalize: 
      # - transform/linux/mactime.vrl
      - ecs_normalize/linux/mactime.vrl
