metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/message'
  os: unix

configuration:
  module: message
  type: process
  disk_only: true
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  name: (?:message)
  path: var/log

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"