version: 1.0
author:
module: syslog
description: Parsing logs from '/var/log/syslog'
os: unix
type: process
requirements:
disk_only: True
no_multithread: True
processor_type: 
  - internal
processor_os: unix
input:
  type: file
  name: (?:syslog)
  path: var/log
output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"
endpoint: "extract_uac\/(.*?)\/"
splunk:
  'linux:syslog':
    name_rex: syslog.*\.jsonl$
    sourcetype: 'linux:syslog'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
    - "_time"
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f%z"
    artifact: "syslog"