metadata:
  version: "2.0"
  author: Typ
  description: Parsing logs from '/var/log/syslog'
  os: unix

configuration:
  module: syslog
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - internal
  processor_os: unix

input:
  type: file
  name: (?:syslog)
  path: var/log

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"

splunk:
  'linux:syslog':
    name_rex: syslog.*\.jsonl$
    sourcetype: 'linux:syslog'
    host_rex: "\/Endpoint_(.*?)\/"
    timestamp_path: 
    - "_time"
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f%z"
    artifact: "syslog"