metadata:
  version: "2.0"
  author: maxspl
  description: Parsing web access logs
  os: unix

configuration:
  module: web_access
  type: process
  disk_only: true
  no_multithread: true
  processor_type:
  - external
  processor_os: unix

tool: 
  path: TurboLP
  cmd: run --module web-access --input {input_file} --output  {output_file}

input:
  type: file
  name: (?:access_log|access\.log)

output:
  type: single_file
  format: json
  output_file: "{endpoint_name}--{module}-{input_file}.jsonl"

endpoint: 
  patterns:
    - r"extract_uac\/(.*?)\/"
  default: "UNKNOWN"