version: 1.0
author: maxspl
description: ANSSI DFIR-OGRE modules
os: windows
modules:
  - ogre-hive-components.yml
  - ogre-chrome-extension.yml
  - ogre-hive-default.yml
  - ogre-system-info.yml
  - ogre-hive-bcd-template.yml
  - ogre-hive-ntuser-dat.yml
  - ogre-chrome-history.yml
  - ogre-evt.yml
  - ogre-wer.yml
  - ogre-srum.yml
  - ogre-recycle-bin.yml
  - ogre-evtx.yml
  - ogre-tcp-connection.yml
  - ogre-lnk-batched.yml
  - ogre-chrome-download-history.yml
  - ogre-list-dll.yml
  - ogre-pca-general-record.yml
  - ogre-hive-usrclass-dat.yml
  - ogre-autoruns.yml
  - ogre-hive-sam.yml
  - ogre-vss-snapshot.yml
  - ogre-registry-reg-system-info.yml
  - ogre-registry-user-profile.yml
  - ogre-registry-amcache-driver.yml
  - ogre-registry-shim-database.yml
  - ogre-registry-certificates-users.yml
  - ogre-registry-autoruns-system.yml
  - ogre-registry-amcache-program.yml
  - ogre-registry-subject-interface-package.yml
  - ogre-registry-certificates-software.yml
  - ogre-registry-recent-app.yml
  - ogre-registry-run-mru.yml
  - ogre-registry-clsid-users.yml
  - ogre-registry-mui-cache.yml
  - ogre-registry-amcache-files.yml
  - ogre-registry-snapshot-exclude.yml
  - ogre-registry-autoruns-user.yml
  - ogre-registry-autoruns-software.yml
  - ogre-registry-bamdam.yml
  - ogre-registry-app-compat-cache.yml
  - ogre-registry-user-assist.yml
  - ogre-registry-network-configuration.yml
  - ogre-registry-acmru.yml
  - ogre-registry-antifishing-file.yml
  - ogre-registry-mass-storage-system.yml
  - ogre-registry-clsid-software.yml
  - ogre-registry-scheduled-task.yml
  - ogre-registry-services-control-set.yml
  - ogre-registry-shell-bag.yml
  - ogre-pca-app-launch.yml
  - ogre-hive-software.yml
  - ogre-volstat.yml
  - ogre-hive-amcache-hve.yml
  - ogre-hive-system.yml
  - ogre-prefetch.yml
  - ogre-hive-elam.yml
  - ogre-activity-cache.yml
  - ogre-firefox-download-history.yml
  - ogre-firefox-extension.yml
  - ogre-usn-info.yml
  - ogre-firefox-history.yml
