version: 1.0
author:
description:
os: windows
modules:
  - anssi_decode.yml
  - amcache.yml
  - browsers.yml
  - collect_info_orc.yml
  - evtx_orc.yml
  - extract_orc.yml
  - hayabusa.yml
  - hives_hkcu.yml
  - hives_hklm.yml
  - jump_list.yml
  - lnk.yml
  - prefetch
  - recycle_bin.yml
  - restore_fs
  - shell_bags.yml
  - shimcache.yml
  - srum.yml
  - win_timeline.yml