metadata:
  version: "1.0"
  id: powershell_history
  author: Typ
  description: PowerShell History → ECS

transformation:
  - set:
      event.original: encode_json!(.)
    conditions:
      - field: event.original
        exists: false
  - set:
      event.dataset:
        value: windows.powershell_history
      event.module:
        value: windows
      event.kind:
        value: event
      event.category:
        value: [process]
      event.type:
        value: [info]
      event.outcome:
        value: success
      event.provider:
        value: PowerShell History
  - custom: |2-
      if exists(.type) {
          type_raw = to_string!(del(.type))
          type_l   = downcase(type_raw)

          .event.code   = type_raw
          .event.action = type_l
      }

      if exists(.line_number) {
          ln_raw = to_string!(del(.line_number))
          ln_int = parse_int(ln_raw) ?? null

          if ln_int != null {
              .event.sequence                 = ln_int
              .powershell.history.line_number = ln_int
          } else {
              .powershell.history.line_number = ln_raw
          }
      }

      if exists(.command) {
          cmd = to_string!(del(.command))

          .process.command_line         = cmd
          .powershell.history.command   = cmd
      }
