metadata:
  version: "1.0"
  id: powershell_history
  author: Typ
  description: Windows PowerShell History JSONL → ECS

transformation:
  - set:
      event.original: encode_json!(.)
    conditions:
      - field: event.original
        exists: false

  - set:
      process.command_line: command
      event.sequence:
        source: line_number
        operation: to_int
      labels.line_number: line_number

  - delete:
      - type
      - line_number
      - command

timeline:
  - id: executed
    message: "PowerShell command was executed: {process.command_line}"
