metadata:
  version: "1.0"
  author: maxspl
  description: Pending at jobs
  os: unix

configuration:
  module: at_jobs
  alt_module: plasma_dispatcher
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: dir
  paths:
    - r"extract_uac.*\/\[root\]$"

output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}--{module}.jsonl"

endpoint:
  patterns:
    - r"extract_uac\/Endpoint_(.*?)\/"
  default: "UNKNOWN"

optional:
  dissector: linux_at_jobs

splunk:
  'linux:at_jobs':
    name_rex: \.jsonl$
    path_suffix: at_jobs
    sourcetype: 'linux:at_jobs'
    host_rex: ([\w\.-]+?)--
    timestamp_path:
        - "at_job_time"
    artifact: "at_jobs"
