metadata:
  version: "1.0"
  author: maxspl
  description: SSH public keys found on disk
  os: unix

configuration:
  module: ssh_pub_key
  alt_module: plasma_dispatcher
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: dir
  paths:
    - r"extract_uac.*\/\[root\]$"

output:
  type: single_file
  format: jsonl
  filename: "{extracted_endpoint}--{module}.jsonl"

extracted:
  - endpoint:
      patterns:
        - r"extract_uac\/Endpoint_(.*?)\/"
      default: "UNKNOWN"

optional:
  dissector: generic_ssh_pub_key

splunk:
  'linux:ssh_pub_key':
    name_rex: r"\.jsonl$"
    path_suffix: ssh_pub_key
    sourcetype: 'linux:ssh_pub_key'
    host_rex: r"([\w\.-]+?)--"
    artifact: "ssh_pub_key"
