metadata:
  version: "1.0"
  author: maxspl
  description: Configured yum/dnf repositories
  os: unix

configuration:
  module: yum_sources
  alt_module: plasma_dispatcher
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
  - internal
  processor_os: unix

input:
  type: dir
  paths:
    - r"extract_uac.*\/\[root\]$"

output:
  type: single_file
  format: jsonl
  filename: "{extracted_endpoint}--{module}.jsonl"

extracted:
  - endpoint:
      patterns:
        - r"extract_uac\/Endpoint_(.*?)\/"
      default: "UNKNOWN"

optional:
  dissector: linux_yum_sources

splunk:
  'linux:yum_sources':
    name_rex: r"\.jsonl$"
    path_suffix: yum_sources
    sourcetype: 'linux:yum_sources'
    host_rex: r"([\w\.-]+?)--"
    artifact: "yum_sources"
