metadata:
  version: "1.0"
  author: maxspl
  description: Parsing of shim_db - using ANSSI DFIR OGRE
  os: windows

configuration:
  module: ogre-registry-shim-database
  type: process
  disk_only: false
  no_multithread: false
  processor_type:
    - external
  processor_os: unix

tool: 
  path: /app/ogre-venv/bin/dfir-ogre
  cmd: >-
    plugin
    --filename "{input_file}"
    --computer_name "{endpoint_name}"
    --output_folder "{output_dir}"
    --plugin_config "/ogre/dfir-ogre-plugin-windows/configuration/registry/shim_database.xml"
    --output_format jsonl
    --output_date_format iso_utc
  source: https://github.com/ANSSI-FR/dfir-ogre
  version: 2.0.0-beta1

input:
  type: file
  paths:
    - r".*/SOFTWARE$"

output:
  type: multiple_files
  format: jsonl
  output_prefix: "{endpoint_name}--{module}-"

endpoint: 
  patterns:
    - r"restore_fs\/(.*?)\/"
    - r"\/Endpoint_(.*?)\/"
  default: "UNKNOWN"

splunk:
  'windows:ogre:registry_shim_database':
    name_rex: '\.jsonl$'
    path_suffix: 'ogre-registry-shim-database'
    sourcetype: 'windows:ogre:registry_shim_database'
    host_rex: ([\w\.-]+)--
    artifact: "hive"
    timestamp_path:
      - "key_modif_time" 
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f%z"
